# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reverse_shell.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13reverse_shell.proto\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"4\n\x0f\x43ommandResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x11\n\tis_active\x18\x02 \x01(\x08\x32L\n\x13ReverseShellService\x12\x35\n\x0cStartSession\x12\x0f.CommandRequest\x1a\x10.CommandResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reverse_shell_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=23
  _globals['_COMMANDREQUEST']._serialized_end=56
  _globals['_COMMANDRESPONSE']._serialized_start=58
  _globals['_COMMANDRESPONSE']._serialized_end=110
  _globals['_REVERSESHELLSERVICE']._serialized_start=112
  _globals['_REVERSESHELLSERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
